defaults_pg: &defaults_pg
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: <%= ENV['USER'] %>
  password:

development:
  <<: *defaults_pg
  database: learnento_development

test:
  <<: *defaults_pg
  database: learnento_test

